III-2164 add parameter for other languages
cultuurnet/calendar-summary pull request #10
Opened 2018-07-10 07:49 UTC by JonasVHG

2018-07-19 14:00 UTC, cyberwolf requested changes
In https://github.com/cultuurnet/calendar-summary/tree/master/src/Permanent there are several cases that specifically and only handle Dutch, should there be some form of multilingual handling for these as well?

There are other areas where things are not translated yet. E.g. in formatedStarted() https://github.com/cultuurnet/calendar-summary/blob/master/src/Period/ExtraSmallPeriodHTMLFormatter.php#L73 and formatNotStarted() https://github.com/cultuurnet/calendar-summary/blob/master/src/Period/ExtraSmallPeriodHTMLFormatter.php#L84

2018-07-19 14:00 UTC, cyberwolf commented on src/Period/ExtraSmallPeriodHTMLFormatter.php
> +    public function __construct($locale)
Old default value is missing here, this would be a BC break causing issues for existing uses of the library.

2018-07-19 14:00 UTC, cyberwolf commented on src/Period/ExtraSmallPeriodPlainTextFormatter.php
> +    public function __construct($locale)
Old default value is missing here, this would be a BC break causing issues for existing uses of the library.

2018-07-19 14:00 UTC, cyberwolf commented on src/Period/LargePeriodHTMLFormatter.php
> +    public function __construct($locale)
Old default value is missing here, this would be a BC break causing issues for existing uses of the library.

2018-07-19 14:00 UTC, cyberwolf commented on src/Period/LargePeriodPlainTextFormatter.php
> +use phpDocumentor\Reflection\Types\This;
Is this used somewhere?

2018-07-19 14:00 UTC, cyberwolf commented on src/Period/LargePeriodPlainTextFormatter.php
> +    public function __construct($locale)
Old default value is missing here, this would be a BC break causing issues for existing uses of the library.

2018-07-19 14:00 UTC, cyberwolf commented on src/Period/MediumPeriodHTMLFormatter.php
> +    public function __construct($locale)
Old default value is missing here, this would be a BC break causing issues for existing uses of the library.

2018-07-19 14:00 UTC, cyberwolf commented on src/Period/MediumPeriodPlainTextFormatter.php
> +    public function __construct($locale)
Old default value is missing here, this would be a BC break causing issues for existing uses of the library.

2018-07-19 14:00 UTC, cyberwolf commented on src/Period/SmallPeriodHTMLFormatter.php
> +    public function __construct($locale)
Old default value is missing here, this would be a BC break causing issues for existing uses of the library.

2018-07-19 14:00 UTC, cyberwolf commented on src/Period/SmallPeriodPlainTextFormatter.php
> +    public function __construct($locale)
Old default value is missing here, this would be a BC break causing issues for existing uses of the library.

2018-07-19 14:00 UTC, cyberwolf commented on src/Timestamps/ExtraSmallTimestampsHTMLFormatter.php
> +    public function __construct($locale)
Old default value is missing here, this would be a BC break causing issues for existing uses of the library.

2018-07-19 14:00 UTC, cyberwolf commented on src/Timestamps/ExtraSmallTimestampsPlainTextFormatter.php
> +    public function __construct($locale)
Old default value is missing here, this would be a BC break causing issues for existing uses of the library.

2018-07-19 14:00 UTC, cyberwolf commented on src/Timestamps/LargeTimestampsHTMLFormatter.php
> +    public function __construct($locale)
Old default value is missing here, this would be a BC break causing issues for existing uses of the library.

2018-07-19 14:00 UTC, cyberwolf commented on src/Timestamps/LargeTimestampsPlainTextFormatter.php
> +    public function __construct($locale)
Old default value is missing here, this would be a BC break causing issues for existing uses of the library.

2018-07-19 14:00 UTC, cyberwolf commented on src/Timestamps/MediumTimestampsHTMLFormatter.php
> +    public function __construct($locale)
Old default value is missing here, this would be a BC break causing issues for existing uses of the library.

2018-07-19 14:00 UTC, cyberwolf commented on src/Timestamps/MediumTimestampsPlainTextFormatter.php
> +    public function __construct($locale)
Old default value is missing here, this would be a BC break causing issues for existing uses of the library.

2018-07-19 14:00 UTC, cyberwolf commented on src/Timestamps/SmallTimestampsHTMLFormatter.php
> +    public function __construct($locale)
Old default value is missing here, this would be a BC break causing issues for existing uses of the library.

2018-07-19 14:00 UTC, cyberwolf commented on src/Timestamps/SmallTimestampsPlainTextFormatter.php
> +    public function __construct($locale)
Old default value is missing here, this would be a BC break causing issues for existing uses of the library.

2020-09-04 10:19 UTC, bertramakers commented
Related ticket has been closed as `Won't Do` so I'm closing this.

2020-09-04 10:19 UTC, closed without merging